import React from 'react'
import { ArrowRight, CalendarDays, FileSignature, FileText, Image, Mail, Pencil } from 'lucide-react'
import { displayDate } from './format.js'
import { splitByToday } from './schedule.js'
import { ScheduleRow } from './SchedulePage.jsx'

export default function ProjectOverview({ project, galleries, invoices, contracts, emails, schedule, canEdit, onOpen, onNew, onStatus, onNavigate, onEdit, onScheduleItem }) {
  const upcoming = splitByToday(schedule).upcoming
  const groups = [['Galleries', galleries, Image], ['Invoices', invoices, FileText], ['Contracts', contracts, FileSignature], ['Email', emails, Mail]]
  return <div className="project-overview"><header className="page-head inner-head"><div><span className="scope-kicker">PROJECT WORKSPACE</span><h1>{project.name}</h1><p>{project.client} · {project.type || 'Photography'} · {project.location || 'Location to be confirmed'}</p></div>{canEdit && <button className="primary" onClick={() => onNew('Email')}>New email <Mail size={16}/></button>}</header><div className="project-summary"><div><span>SHOOT DATE</span><strong>{displayDate(project.date) || 'To be scheduled'}</strong></div><div><span>STATUS</span><strong>{project.status || 'Planning'}</strong></div><div><span>PROGRESS</span><strong>{project.progress || 0}%</strong></div></div>{canEdit && <div className="project-actions"><button className="secondary" onClick={onEdit}><Pencil size={15}/> Edit project</button>{project.status !== 'Delivered' && <button className="secondary" onClick={onStatus}>Mark project delivered</button>}</div>}<section className="project-schedule"><div className="section-heading"><h2><CalendarDays size={20}/> Schedule</h2>{canEdit && <button onClick={() => onNew('Schedule')}>Add event</button>}</div>{upcoming.length ? <div className="schedule-list">{upcoming.slice(0, 4).map(item => <ScheduleRow key={item.key} item={item} onOpen={onScheduleItem} showProject={false}/>)}</div> : <div className="empty-list">Nothing scheduled for this project.</div>}{upcoming.length > 4 && <button className="project-view-all" onClick={() => onNavigate('Schedule')}>View all {upcoming.length} <ArrowRight size={15}/></button>}</section><div className="project-collections">{groups.map(([section, rows, Icon]) => <section key={section}><div className="section-heading"><h2><Icon size={20}/> {section}</h2>{canEdit && section !== 'Email' && <button onClick={() => onNew(section)}>New {{ Galleries: 'gallery', Invoices: 'invoice', Contracts: 'contract' }[section]}</button>}</div>{rows.length ? rows.slice(0, 3).map(item => <button className="project-record" key={item.id} onClick={() => onOpen(section, item)}><span><strong>{item.title || item.subject}</strong><small>{item.status || item.updated}</small></span><ArrowRight size={16}/></button>) : <div className="empty-list">No {section.toLowerCase()} in this project yet.</div>}{rows.length > 3 && <button className="project-view-all" onClick={() => onNavigate(section)}>View all {rows.length} <ArrowRight size={15}/></button>}</section>)}</div></div>
}
