import React from 'react'
import { ArrowRight, X } from 'lucide-react'
import { sectionActions } from './format.js'

export default function RecordModal({ section, projects, scope, onClose, onSubmit }) {
  const fields = {
    Clients: [['name', 'Full name', 'text', 'e.g. Jamie Lee', true], ['email', 'Email address', 'email', 'jamie@example.com', true], ['phone', 'Phone number', 'tel', '(415) 555-0123', false]],
    Galleries: [['title', 'Gallery name', 'text', 'e.g. Jamie & Robin', true], ['client', 'Client name', 'text', 'e.g. Jamie Lee', true], ['email', 'Client email', 'email', 'jamie@example.com', true]],
  }
  if (section === 'Help') return <div className="modal-backdrop" onMouseDown={onClose}><div className="modal info-modal" onMouseDown={e => e.stopPropagation()}><button className="modal-close" onClick={onClose} aria-label="Close"><X size={20}/></button><h2>Help</h2><p>Create an invoice or contract, open it to download the PDF, then choose Email PDF to attach it to a message.</p><div className="info-actions"><button className="primary" onClick={onClose}>Done</button></div></div></div>
  return <div className="modal-backdrop" onMouseDown={onClose}><div className="modal" onMouseDown={e => e.stopPropagation()}><div className="modal-head"><div><span>ADD TO YOUR STUDIO</span><h2>{sectionActions[section]}</h2></div><button className="modal-close" onClick={onClose} aria-label="Close"><X size={20}/></button></div><form onSubmit={onSubmit}>{section === 'Galleries' && <label>Project<select name="projectId" required defaultValue={projects.some(project => String(project.id) === scope) ? scope : ''}><option value="">Choose a project</option>{projects.map(project => <option key={project.id} value={String(project.id)}>{project.name}</option>)}</select></label>}{fields[section].map(([name, label, type, placeholder, required]) => <label key={name}>{label}{type === 'select' ? <select name={name}>{placeholder.split(',').map(v => <option key={v}>{v}</option>)}</select> : type === 'textarea' ? <textarea name={name} rows="4" placeholder={placeholder} required={required}/> : <input name={name} type={type} placeholder={placeholder} required={required} defaultValue={section === 'Galleries' && name === 'client' ? projects.find(project => String(project.id) === scope)?.client || '' : section === 'Galleries' && name === 'email' ? projects.find(project => String(project.id) === scope)?.clientEmail || '' : undefined}/>}</label>)}<div className="modal-actions"><button type="button" className="secondary" onClick={onClose}>Cancel</button><button type="submit" className="primary">Create <ArrowRight size={16}/></button></div></form></div></div>
}
